---

- name: Create download directory
  tempfile:
    state: directory
    suffix: golang_dl
  register: go_temp_download_dir
  changed_when: false

- name: Download the Go archive
  get_url:
    url: "{{ go_download_url }}"
    dest: "{{go_temp_download_dir.path}}/{{ go_download_filename }}"
    checksum: "{{ go_download_checksum }}"

- name: Extract the Go tarball if Go is not yet installed or not the desired version
  unarchive:
    src: "{{ go_temp_download_dir.path}}/{{ go_download_filename}}"
    dest: "{{ go_install_path }}"
    copy: no


