---
- name: get GOROOT from config
  stat: path='{{ go_install_path }}/{{ go_install_dirname }}'
  register: go_conf_goroot

- name: get binary from config
  stat: path='{{ go_install_path }}/{{ go_install_dirname }}/bin/go'
  register: go_conf_goroot_bin

- name: Register the conf version (if any)
  command: "{{ go_conf_goroot_bin.stat.path }} version"
  ignore_errors: yes
  register: go_conf_goroot_bin_version_output
  changed_when: false

- name: Register conf binary state
  set_fact:
    go_state: "{{ 'current' if go_conf_goroot_bin_version_output.stdout is defined and (go_conf_goroot_bin_version_output.stdout|string).strip() == go_version_expected_stdout else 'present' if go_conf_goroot_bin.stat.exists else 'absent' }}"


- name: set go_state
  set_fact:
    go_root: "{{ go_conf_goroot.stat.path}}"

- name: remove old version
  file:
    path: '{{go_goroot}}'
    state: absent
  when: go_state == 'present'
